project:
  type: website
  output-dir: docs
  resources:
    - project_outputs/**

website:
  title: "Breakout Strategy Backtest"
  navbar:
    left:
      - href: index.qmd
        text: Project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
